name: Release

on:
   push:
      branches:
         - main

jobs:
   release:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         issues: write
         pull-requests: write
      steps:
         - uses: actions/checkout@v4
           with:
              persist-credentials: false

         - uses: actions/setup-node@v4
           with:
              node-version: "lts/iron"
              cache: "npm"

         - run: npm ci

         - run: npm run build

         - run: npx semantic-release
           env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
